name: Docker Image CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  dockerimage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set build arguments
        run: |
          echo "VERSION=latest" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "VCS_REF=${GITHUB_SHA}" >> $GITHUB_ENV
      - name: HelloWorld smoke-test
        run: |
          dotnet run --project HelloWorld
